### ISSUE TITLE
Suggested Week 5 Schedule

### ISSUE THREAD

**Issue by m4v15** [m4v15/master-reference#17]
Current Schedule:
![screen shot 2018-11-12 at 14 27 05](https://user-images.githubusercontent.com/23310908/48347577-4a84f100-e687-11e8-8537-bc93485baaa1.png)
Suggested Schedule:
![screen shot 2018-11-12 at 14 27 14](https://user-images.githubusercontent.com/23310908/48347587-4fe23b80-e687-11e8-8992-f312d50b3dd2.png)

Changes:

- Expand request module to talk about other core node modules (aisha has developed this workshop [here](https://github.com/astroash/going-on-a-bear-hunt)). This would go where the current error handling workshop is.
- Add a bit more of an introduction to the error handling workshop, this replaces the Node shell workshop.
- Keep the first part of the node shell workshop to replace the request module MC
- also add a better intro to linters

**Comment by mattlub** [comment]
core module sounds good.

can you do just a bit of node shell? Why remove the request one? Does it usually not go well.

**Comment by ghassanmas** [comment]
Yeah I also like vote to do node shell

**Comment by m4v15** [comment]
Node shell is split into lesson 1 and lesson 2 so seems easy to split.

Sorry, maybe I wasn't clear - Aisha's workshop _is_ the request morning challenge, but built out more to explore other core node modules - it is not removed.

Basically all this change does is give take time from the node shell workshop and give it to talking about core node modules. I think it's probably worth doing - I like the node shell workshop and wouldn't want to lose it completely but maybe time spent on the core modules is better...
